[platformio]
boards_dir = boards
lib_dir = lib
src_dir = src
include_dir = include

[env:esp32-s3-n16r8v]
platform = espressif32
framework = arduino
board = esp32-s3-n16r8v
monitor_filters = esp32_exception_decoder
monitor_speed = 115200
upload_speed = 921600
build_flags = 
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_LVGL_H_INCLUDE_SIMPLE
    -I include/
lib_deps =
  lvgl/lvgl@^8.3.11
  bblanchon/ArduinoJson@6.21.3
  bitbank2/JPEGDEC@^1.8.2
lib_extra_dirs = lib;
; ตั้งค่า Partition Table ให้มีพื้นที่สำหรับ App มากขึ้น
; สำหรับโปรเจกต์ที่มี LVGL และไดรเวอร์จอ
board_build.partitions = partitions_ota.csv